### ISSUE TITLE
Quote for Hero card without sidekick

### ISSUE THREAD

**Issue by Conro101** [JonathanGuberman/unmatched_maker#20]
Right now, if a hero has zero sidekicks, there's just a big black box at the bottom. Newer characters without sidekicks like [Bruce Lee](http://puu.sh/EJoaA/c375521f95.png) or the [Raptors](https://i.imgur.com/QqTyr4h.png) have a space for a quote in that spot. It'd be nice to have something similar.

**Comment by JonathanGuberman** [comment]
This has been fixed on Unmatched.cards
