### ISSUE TITLE
[Feature Idea] Card/Table Simulator

### ISSUE THREAD

**Issue by JollyGrin** [JonathanGuberman/unmatched_maker#21]
![image](https://user-images.githubusercontent.com/28109194/77829479-a805ca80-7122-11ea-9a0d-72d0e5fcee2e.png)

Tappedout.net has a tool that let's you playtest drawing & placing cards on a table. No rule enforcement, just simple functions to draw, place, tap, flip, and discard. 

Yet with Unmatched, the card operations are extremely simple. You just need a deck, discard pile, hand, and ability to place cards and flip them. Imagine a link that transforms a variant into a playtest in the browser, with the deck loaded up. 

With a tablet browser, you could quickly playtest and edit decks on the fly using any item as a figurine to represent your fighters without having to print anything. Then when satisfied you can print out card stock.

This would further revolutionize the variant homebrew scene :D

**Comment by JollyGrin** [comment]
Hey! Ended up just making this myself. I used the json format you use to design cards so people can easily take creations in the Deck Maker into the playtester

Demo: https://unbrewed.xyz

Git: https://github.com/JollyGrin/unbrewed

**Comment by JonathanGuberman** [comment]
@JollyGrin That's awesome! Great work! Have you considered grabbing some of the code from my repo to get the card styling? I'd love to work on that sometime, but I don't know when I'll have the time.
