### ISSUE TITLE
Make card backs visible in interface and do something other than in TTS Export

### ISSUE THREAD

**Issue by JonathanGuberman** [JonathanGuberman/unmatched_maker#35]

**Comment by JonathanGuberman** [comment]
I like the idea of flipping over the card to set the back, but on the other hand we might want the back to always be visible somewhere. It's a conflict between usability and finesse.

**Comment by fanaka66** [comment]
Yes please!  I couldn’t get the card back to export to TTS because I forgot to change the 0 to a 1 for a Dropbox link.  It’s easy to remember in the normal interface, because you see the card doesn’t show up right away.

**Comment by JonathanGuberman** [comment]
This is done. I'd like to add the option to add a border and the deck names to any image. It wouldn't be hard, but I figure I'll probably wrap it in with #14 .
