### ISSUE TITLE
Search/Filter on Fields Besides Deck Name

### ISSUE THREAD

**Issue by gmccarthy0188** [JonathanGuberman/unmatched_maker#47]
In our personal Fan Decks, sorting by Published Yes/No is not working. Filtering by Published Yes/No would also be handy (Right now I am using a tag to accomplish this instead, and manually maintaining it on each deck.)

Searching and Filtering based on Creator name would also be handy in the general fan decks area.

**Comment by JonathanGuberman** [comment]
Would you want separate search fields, or would one universal search be sufficient?

**Comment by gmccarthy0188** [comment]
I think one universal field would suffice?

**Comment by JonathanGuberman** [comment]
I started on this, and got carried away:
- You can sort by published state on your own deck page.
- The deck filter box looks for the words in both the deck name and the creator name.
- Previously, search was for the exact term (e.g., `solid metal` would not have returned decks with `metal gear solid`); now, search is tokenized, so word order doesn't matter. To search for an exact term, enclose it in quotes (e.g., `"solid metal"`).
- You can restrict a search term by prepending it with `u:`, `user:`, `c:`, `creator:`, `n:`, `name:`, `d:`, or `deck:`. E.g., `u:metal d:"gear solid" snake` will show decks that have `metal` in the username, `gear solid` in the deck name, and `snake` in either the username or the deck name.
- You can negate a search term by including a `-` (minus sign) in front of it, with no spaces. E.g., `u:metal -d:"gear solid" snake` will show decks that have `metal` in the username and `snake` in either the username or the deck name, but does NOT have the phrase `gear solid` in the deck name.
