### ISSUE TITLE
A simple hero card request

### ISSUE THREAD

**Issue by ColbyRuby** [JonathanGuberman/unmatched_maker#69]
Could we get the option to have no sidekicks? Thank you!

**Comment by JonathanGuberman** [comment]
The option is already there. When you hover over the Character Card, a large "x1" appears to the right of the bottom right of the card. 

![image](https://user-images.githubusercontent.com/507528/116588318-64632e80-a8e9-11eb-9bb9-1255cc30e0d3.png)

If you hover over that and click the down arrow, you can change it to zero.

![image](https://user-images.githubusercontent.com/507528/116588533-ae4c1480-a8e9-11eb-8425-4ab221263ece.png)

If you'd like, you can then click in the empty space to add a quote:

![image](https://user-images.githubusercontent.com/507528/116588430-8e1c5580-a8e9-11eb-8229-94df668bd873.png)
