### ISSUE TITLE
Add cut lines when printing

### ISSUE THREAD

**Issue by JonathanGuberman** [JonathanGuberman/unmatched_maker#7]

**Comment by tsilver33** [comment]
This one has my vote for top of the list. Printing out my own custom character was a nightmare, and none of the cuts came out right. Alternatively even just a black border option would work wonders. As it is though, the white borders on the cards makes cutting them a real issue when printed onto white cardstock.

Thanks again for all the work you've done on this Jonathan. It's been a lot of fun to use. :)

**Comment by JonathanGuberman** [comment]
I'm embarrassed to admit that, since I've been using the "print and play" style exclusively, I didn't even think about how difficult it'd be to cut out the white borders! I will try to add cut lines, but I'll definitely add some sort of borders.

Thanks for taking the time to comment on the issues, and I'm so glad you hear you've been enjoying it!

**Comment by JonathanGuberman** [comment]
It doesn't work perfectly, but this has now been sort-of resolved. I'm going to close this for now because I don't see a better way to make it work for the time being.
